# Generated by Django 3.1.7 on 2021-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
